apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Deployment
metadata:
  name: web-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-game
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: web-game
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: web-game
        image: faroprodregistry.azurecr.io/web-game:tag
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
